services:
  referee-coach-probasket-db:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=probasket
      - POSTGRES_PASSWORD=probasket
      - POSTGRES_DB=probasket
    ports:
      - "5432:5432"
